apiVersion: v1
kind: Service
metadata:
  name: fullstack-service
spec:
  type: NodePort
  selector:
    app: frontend  # Change this for backend if necessary
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001
